const graphData = {
  nodes: [
    { id: "root", label: "Peace Lab 知识库", group: 0, level: 0, description: "平静实验室 · 多维度身心疗愈知识体系", fileCount: 2667 },

    { id: "p1", label: "智慧传承", group: 1, level: 1, description: "瑜伽哲学、禅宗、道家、佛教、太极拳、黄帝内经、东西方哲学", fileCount: 405 },
    { id: "p2", label: "心智与心理学", group: 2, level: 1, description: "心理流派、临床干预、冥想技术、感官疗法、自我调节", fileCount: 864 },
    { id: "p3", label: "生命科学", group: 3, level: 1, description: "生物黑客、神经科学、身心能量、营养学、性学、死亡教育", fileCount: 353 },
    { id: "p4", label: "人文与艺术", group: 4, level: 1, description: "艺术史与疗法、芭蕾、古典音乐、影音媒体、深度阅读", fileCount: 607 },
    { id: "p5", label: "实践与增长", group: 5, level: 1, description: "超级个体、效率、沟通、写作、TED讲座、任务管理", fileCount: 420 },

    { id: "1-philosophy", label: "哲学体系", group: 1, level: 2, parent: "p1", description: "东亚/南亚/西方哲学全覆盖", fileCount: 80 },
    { id: "1-religions", label: "宗教与灵性", group: 1, level: 2, parent: "p1", description: "佛教、禅宗、道家、藏密、基督教、伊斯兰教", fileCount: 180 },
    { id: "1-tai-chi", label: "太极拳", group: 1, level: 2, parent: "p1", description: "太极流派、功法、神经科学证据", fileCount: 7 },
    { id: "1-tcm", label: "黄帝内经", group: 1, level: 2, parent: "p1", description: "内经养生、经典方剂", fileCount: 6 },
    { id: "1-yoga", label: "瑜伽", group: 1, level: 2, parent: "p1", description: "瑜伽哲学、体式、冥想、大师传承、师资培训", fileCount: 55 },

    { id: "2-meditation", label: "冥想", group: 2, level: 2, parent: "p2", description: "核心方法、大师传承、课程体系、MBSR", fileCount: 120 },
    { id: "2-psychology", label: "心理学", group: 2, level: 2, parent: "p2", description: "基础/临床/压力/发展/社会/行为/躯体/调节/应用/专题", fileCount: 350 },
    { id: "2-relationships", label: "关系心理学", group: 2, level: 2, parent: "p2", description: "婚恋、出轨、育儿、性别动力学、情绪银行", fileCount: 60 },
    { id: "2-therapy", label: "疗法体系", group: 2, level: 2, parent: "p2", description: "CBT/DBT/ACT/MBCT/EMDR/森田/感官/森林/香道", fileCount: 80 },

    { id: "3-biology", label: "生物医学", group: 3, level: 2, parent: "p3", description: "运动科学、长寿、心血管、肠道菌群、免疫", fileCount: 200 },
    { id: "3-foods", label: "营养与断食", group: 3, level: 2, parent: "p3", description: "断食方案、咖啡、茶、代谢优化", fileCount: 20 },
    { id: "3-sexuality", label: "性学研究", group: 3, level: 2, parent: "p3", description: "性心理学、性教育、性焦虑", fileCount: 15 },
    { id: "3-death", label: "死亡教育", group: 3, level: 2, parent: "p3", description: "死亡哲学、临终关怀", fileCount: 8 },

    { id: "4-arts", label: "艺术与疗愈", group: 4, level: 2, parent: "p4", description: "艺术疗法、芭蕾、书法、摄影、戏剧、园艺", fileCount: 120 },
    { id: "4-media", label: "影音媒体", group: 4, level: 2, parent: "p4", description: "电影、电视剧、古典音乐、播客、动漫", fileCount: 250 },
    { id: "4-literature", label: "文学", group: 4, level: 2, parent: "p4", description: "文学疗法、中外经典、诗歌、宋词", fileCount: 60 },
    { id: "4-reading", label: "阅读与书籍", group: 4, level: 2, parent: "p4", description: "深度阅读推荐", fileCount: 30 },

    { id: "5-personal", label: "个人发展", group: 5, level: 2, parent: "p5", description: "超级个体、效率、心力、心流、习惯", fileCount: 150 },
    { id: "5-communication", label: "沟通技能", group: 5, level: 2, parent: "p5", description: "高效沟通、非防御沟通、结构化表达、谈判", fileCount: 20 },
    { id: "5-writing", label: "写作", group: 5, level: 2, parent: "p5", description: "创意写作、文学批评、技术写作", fileCount: 20 },
    { id: "5-talks", label: "讲座", group: 5, level: 2, parent: "p5", description: "TED Talks 150+领域框架、一席讲座", fileCount: 80 },

    { id: "1-east-asian", label: "东亚哲学", group: 1, level: 3, parent: "1-philosophy", description: "儒、道、法、兵、易 + 日韩越", fileCount: 30 },
    { id: "1-south-asian", label: "南亚哲学", group: 1, level: 3, parent: "1-philosophy", description: "吠檀多、数论、奥义书", fileCount: 6 },
    { id: "1-western-phil", label: "西方哲学", group: 1, level: 3, parent: "1-philosophy", description: "前苏格拉底→当代 · 分析/大陆/存在主义", fileCount: 44 },

    { id: "1-buddhism", label: "佛教", group: 1, level: 3, parent: "1-religions", description: "核心教义、经典、部派、密宗、戒律", fileCount: 90 },
    { id: "1-zen", label: "禅宗", group: 1, level: 3, parent: "1-religions", description: "五家宗派、公案、禅修方法", fileCount: 10 },
    { id: "1-dao", label: "道家", group: 1, level: 3, parent: "1-religions", description: "道德经、庄子、内丹、养生", fileCount: 12 },
    { id: "1-tibetan", label: "藏传佛教", group: 1, level: 3, parent: "1-religions", description: "四大派、前行、脉轮、中阴", fileCount: 14 },
    { id: "1-christianity", label: "基督教", group: 1, level: 3, parent: "1-religions", description: "圣经神学、历史发展、敬拜实践", fileCount: 5 },
    { id: "1-catholicism", label: "天主教", group: 1, level: 3, parent: "1-religions", description: "天主教义、传统与仪式", fileCount: 3 },
    { id: "1-orthodox", label: "东正教", group: 1, level: 3, parent: "1-religions", description: "东正教神学与灵修", fileCount: 2 },
    { id: "1-islam", label: "伊斯兰教", group: 1, level: 3, parent: "1-religions", description: "古兰经、伊斯兰哲学与苏菲", fileCount: 3 },
    { id: "1-legalist", label: "法家", group: 1, level: 3, parent: "1-religions", description: "韩非子、商君书、管理心理学", fileCount: 3 },
    { id: "1-syncretism", label: "三教合一", group: 1, level: 3, parent: "1-religions", description: "儒释道融合、唯识与阳明比较", fileCount: 2 },
    { id: "1-rel-psych", label: "宗教心理学", group: 1, level: 3, parent: "1-religions", description: "理论模型、临床应用、跨文化", fileCount: 6 },
    { id: "1-wisdom", label: "智慧传统", group: 1, level: 3, parent: "1-religions", description: "克里希那穆提、萨满、卡巴拉、茶道", fileCount: 12 },

    { id: "1-tcm-classics", label: "医学经典", group: 1, level: 3, parent: "1-tcm", description: "素问、灵枢、伤寒论、金匮要略", fileCount: 5 },

    { id: "1-yoga-asana", label: "体式库", group: 1, level: 3, parent: "1-yoga", description: "站/坐/前弯/后弯/扭转/倒立等 13 类", fileCount: 14 },
    { id: "1-yoga-masters", label: "瑜伽大师", group: 1, level: 3, parent: "1-yoga", description: "古代→当代→行业领袖→东亚", fileCount: 20 },
    { id: "1-yoga-career", label: "瑜伽职业", group: 1, level: 3, parent: "1-yoga", description: "商业模式、职业路径、个人品牌、保险", fileCount: 8 },
    { id: "1-yoga-training", label: "师资培训", group: 1, level: 3, parent: "1-yoga", description: "教学方法、评估体系、认证对比", fileCount: 6 },
    { id: "1-yoga-six", label: "那洛六瑜伽", group: 1, level: 3, parent: "1-yoga", description: "拙火、幻身、光明、梦瑜伽、中阴、迁识", fileCount: 3 },
    { id: "1-yoga-safety", label: "瑜伽安全", group: 1, level: 3, parent: "1-yoga", description: "损伤预防、不良反应", fileCount: 2 },

    { id: "2-med-overview", label: "冥想概览", group: 2, level: 3, parent: "2-meditation", description: "核心方法、脑科学、临床应用", fileCount: 15 },
    { id: "2-med-masters", label: "冥想大师", group: 2, level: 3, parent: "2-meditation", description: "古代佛教/中国/印度/藏传/西方先驱", fileCount: 15 },
    { id: "2-med-course", label: "冥想课程", group: 2, level: 3, parent: "2-meditation", description: "种子课程、脑科学、呼吸、直指", fileCount: 10 },
    { id: "2-med-guided", label: "引导脚本", group: 2, level: 3, parent: "2-meditation", description: "身体扫描、正念呼吸、慈心", fileCount: 4 },
    { id: "2-med-mbsr", label: "MBSR正念减压", group: 2, level: 3, parent: "2-meditation", description: "八周课程、评估工具", fileCount: 3 },
    { id: "2-med-direct", label: "直指冥想", group: 2, level: 3, parent: "2-meditation", description: "直指vs正念、神经科学、传承", fileCount: 9 },
    { id: "2-med-mandala", label: "坛城冥想", group: 2, level: 3, parent: "2-meditation", description: "坛城技术、传统、神经科学、临床", fileCount: 6 },
    { id: "2-med-satir", label: "萨提亚模式", group: 2, level: 3, parent: "2-meditation", description: "冰山模型、沟通姿态、转化过程", fileCount: 6 },
    { id: "2-med-tm", label: "超觉冥想", group: 2, level: 3, parent: "2-meditation", description: "TM技术、研究证据", fileCount: 2 },
    { id: "2-med-vipassana", label: "内观冥想", group: 2, level: 3, parent: "2-meditation", description: "内观方法与修习", fileCount: 2 },
    { id: "2-med-chinese", label: "中国冥想传统", group: 2, level: 3, parent: "2-meditation", description: "静坐、中医冥想、本土化", fileCount: 5 },
    { id: "2-med-career", label: "冥想职业", group: 2, level: 3, parent: "2-meditation", description: "商业模式、社区、数字产业", fileCount: 7 },
    { id: "2-med-training", label: "冥想师资", group: 2, level: 3, parent: "2-meditation", description: "教学方法、评估、伦理", fileCount: 5 },

    { id: "2-psych-foundations", label: "基础理论", group: 2, level: 3, parent: "2-psychology", description: "流派概述、积极心理学、人格Big Five/MBTI/九型", fileCount: 40 },
    { id: "2-psych-clinical", label: "临床心理", group: 2, level: 3, parent: "2-psychology", description: "焦虑/抑郁/恐惧/创伤/危机/自杀干预", fileCount: 50 },
    { id: "2-psych-stress", label: "压力与HPA轴", group: 2, level: 3, parent: "2-psychology", description: "慢性压力、皮质醇、慢性疲劳、AI技能", fileCount: 25 },
    { id: "2-psych-dev", label: "发展心理", group: 2, level: 3, parent: "2-psychology", description: "青少年、儿童、中年危机、更年期", fileCount: 30 },
    { id: "2-psych-social", label: "社会心理", group: 2, level: 3, parent: "2-psychology", description: "友谊、孤独、仇恨、政治心理、乡村", fileCount: 25 },
    { id: "2-psych-behav", label: "行为与成瘾", group: 2, level: 3, parent: "2-psychology", description: "成瘾、色情依赖、囤积、恋尸、拖延", fileCount: 20 },
    { id: "2-psych-somatic", label: "躯体与睡眠", group: 2, level: 3, parent: "2-psychology", description: "情绪调节、睡眠、放松、躯体体验", fileCount: 30 },
    { id: "2-psych-selfreg", label: "自我调节", group: 2, level: 3, parent: "2-psychology", description: "反焦虑/反强迫/接地/容纳/自悲/自信", fileCount: 30 },
    { id: "2-psych-applied", label: "应用心理", group: 2, level: 3, parent: "2-psychology", description: "职业、倦怠、教育、节日、消费", fileCount: 20 },
    { id: "2-psych-special", label: "特别专题", group: 2, level: 3, parent: "2-psychology", description: "梦境、虚无、家排、丧亲、贫苦、中医心理", fileCount: 25 },

    { id: "2-rel-infidelity", label: "出轨", group: 2, level: 3, parent: "2-relationships", description: "出轨类型、被背叛创伤、信任重建", fileCount: 9 },
    { id: "2-rel-marriage", label: "婚姻", group: 2, level: 3, parent: "2-relationships", description: "婚姻沟通、冷战、无性婚姻、家暴、离婚", fileCount: 14 },
    { id: "2-rel-dating", label: "约会心理", group: 2, level: 3, parent: "2-relationships", description: "约会策略、依恋类型、择偶心理", fileCount: 17 },
    { id: "2-rel-gender", label: "性别动力学", group: 2, level: 3, parent: "2-relationships", description: "媚男/厌男/媚女/厌女", fileCount: 5 },
    { id: "2-rel-eba", label: "情绪银行", group: 2, level: 3, parent: "2-relationships", description: "情感账户、存取款模型", fileCount: 3 },
    { id: "2-rel-love", label: "爱", group: 2, level: 3, parent: "2-relationships", description: "爱的类型、爱情三角理论", fileCount: 3 },
    { id: "2-rel-parenting", label: "育儿", group: 2, level: 3, parent: "2-relationships", description: "理解孩子、亲子关系", fileCount: 2 },
    { id: "2-rel-casual", label: "随意性行为", group: 2, level: 3, parent: "2-relationships", description: "随意性心理", fileCount: 2 },
    { id: "2-rel-cultural", label: "跨文化视角", group: 2, level: 3, parent: "2-relationships", description: "关系跨文化分析", fileCount: 2 },
    { id: "2-rel-clinical", label: "临床指南", group: 2, level: 3, parent: "2-relationships", description: "关系治疗临床手册", fileCount: 2 },
    { id: "2-rel-digital", label: "数字时代关系", group: 2, level: 3, parent: "2-relationships", description: "数字时代对关系的影响", fileCount: 2 },
    { id: "2-rel-diverse", label: "多元群体", group: 2, level: 3, parent: "2-relationships", description: "多元群体视角", fileCount: 2 },
    { id: "2-rel-impact", label: "影响分析", group: 2, level: 3, parent: "2-relationships", description: "关系影响比较", fileCount: 2 },
    { id: "2-rel-legal", label: "法律伦理", group: 2, level: 3, parent: "2-relationships", description: "关系中的法律与伦理", fileCount: 2 },

    { id: "2-ther-cbt", label: "CBT认知行为", group: 2, level: 3, parent: "2-therapy", description: "认知行为疗法", fileCount: 2 },
    { id: "2-ther-dbt", label: "DBT辩证行为", group: 2, level: 3, parent: "2-therapy", description: "辩证行为疗法", fileCount: 3 },
    { id: "2-ther-act", label: "ACT接纳承诺", group: 2, level: 3, parent: "2-therapy", description: "接纳承诺疗法", fileCount: 2 },
    { id: "2-ther-mbct", label: "MBCT正念认知", group: 2, level: 3, parent: "2-therapy", description: "正念认知疗法", fileCount: 2 },
    { id: "2-ther-cft", label: "CFT慈悲聚焦", group: 2, level: 3, parent: "2-therapy", description: "慈悲聚焦疗法", fileCount: 2 },
    { id: "2-ther-emdr", label: "EMDR眼动脱敏", group: 2, level: 3, parent: "2-therapy", description: "眼动脱敏与再加工", fileCount: 2 },
    { id: "2-ther-tfcbt", label: "TF-CBT创伤焦点", group: 2, level: 3, parent: "2-therapy", description: "创伤焦点认知行为", fileCount: 2 },
    { id: "2-ther-cbasp", label: "CBASP", group: 2, level: 3, parent: "2-therapy", description: "认知行为分析系统", fileCount: 2 },
    { id: "2-ther-morita", label: "森田疗法", group: 2, level: 3, parent: "2-therapy", description: "顺其自然、为所当为", fileCount: 3 },
    { id: "2-ther-oh", label: "OH卡疗法", group: 2, level: 3, parent: "2-therapy", description: "OH卡投射疗法", fileCount: 5 },
    { id: "2-ther-focus", label: "焦点疗法", group: 2, level: 3, parent: "2-therapy", description: "焦点解决短期治疗", fileCount: 4 },
    { id: "2-ther-game", label: "游戏疗法", group: 2, level: 3, parent: "2-therapy", description: "游戏治疗", fileCount: 2 },
    { id: "2-ther-ipt", label: "IPT人际心理", group: 2, level: 3, parent: "2-therapy", description: "人际心理治疗", fileCount: 2 },
    { id: "2-ther-sensory", label: "感官疗法", group: 2, level: 3, parent: "2-therapy", description: "视觉/听觉/触觉/舞动/自然", fileCount: 14 },
    { id: "2-ther-forest", label: "森林疗法", group: 2, level: 3, parent: "2-therapy", description: "森林浴、自然暴露恢复", fileCount: 3 },
    { id: "2-ther-incense", label: "香道疗法", group: 2, level: 3, parent: "2-therapy", description: "香道历史、临床方案、艾灸", fileCount: 15 },
    { id: "2-ther-direct", label: "直指疗法", group: 2, level: 3, parent: "2-therapy", description: "直指觉醒与疗愈", fileCount: 2 },

    { id: "3-exercise", label: "运动科学", group: 3, level: 3, parent: "3-biology", description: "力量/有氧/功能/处方/恢复", fileCount: 7 },
    { id: "3-aging", label: "抗衰老", group: 3, level: 3, parent: "3-biology", description: "端粒/表观遗传/NAD+/热量限制", fileCount: 5 },
    { id: "3-cardio", label: "心血管", group: 3, level: 3, parent: "3-biology", description: "心率变异、心血管心理", fileCount: 4 },
    { id: "3-gut", label: "肠道菌群", group: 3, level: 3, parent: "3-biology", description: "肠脑轴、饮食干预", fileCount: 4 },
    { id: "3-immune", label: "免疫与炎症", group: 3, level: 3, parent: "3-biology", description: "慢性炎症、心理神经免疫", fileCount: 5 },
    { id: "3-brain", label: "脑科学", group: 3, level: 3, parent: "3-biology", description: "神经反馈、DMN、BCI、EEG", fileCount: 8 },
    { id: "3-hpa", label: "HPA轴", group: 3, level: 3, parent: "3-biology", description: "压力响应、调节干预", fileCount: 6 },
    { id: "3-weight", label: "减重科学", group: 3, level: 3, parent: "3-biology", description: "营养/运动/心理/行为整合", fileCount: 8 },
    { id: "3-tuina", label: "推拿", group: 3, level: 3, parent: "3-biology", description: "手法标准、经络穴位、现代研究", fileCount: 8 },
    { id: "3-spa", label: "SPA水疗", group: 3, level: 3, parent: "3-biology", description: "SPA技术、生理心理效应", fileCount: 8 },
    { id: "3-skin", label: "皮肤疾病", group: 3, level: 3, parent: "3-biology", description: "湿疹、花斑癣、临床路径", fileCount: 6 },
    { id: "3-floaters", label: "飞蚊症", group: 3, level: 3, parent: "3-biology", description: "飞蚊症研究、预防、心理适应", fileCount: 9 },
    { id: "3-breathwork", label: "呼吸法", group: 3, level: 3, parent: "3-biology", description: "调息、生物黑客呼吸", fileCount: 3 },
    { id: "3-women", label: "女性健康", group: 3, level: 3, parent: "3-biology", description: "月经、生育、更年期", fileCount: 4 },
    { id: "3-bp", label: "血压调节", group: 3, level: 3, parent: "3-biology", description: "晨间血压、临床实践", fileCount: 3 },
    { id: "3-energy", label: "能量恢复", group: 3, level: 3, parent: "3-biology", description: "身心能量恢复", fileCount: 2 },
    { id: "3-office-neck", label: "肩颈放松", group: 3, level: 3, parent: "3-biology", description: "办公肩颈放松", fileCount: 2 },
    { id: "3-office-eye", label: "办公护眼", group: 3, level: 3, parent: "3-biology", description: "办公室眼部放松", fileCount: 2 },
    { id: "3-sleep-stretch", label: "睡前拉伸", group: 3, level: 3, parent: "3-biology", description: "睡前拉伸方案", fileCount: 2 },
    { id: "3-stretch", label: "拉伸", group: 3, level: 3, parent: "3-biology", description: "拉伸疗法", fileCount: 3 },
    { id: "3-pain", label: "疼痛科学", group: 3, level: 3, parent: "3-biology", description: "慢性疼痛管理", fileCount: 3 },
    { id: "3-back-pain", label: "腰痛", group: 3, level: 3, parent: "3-biology", description: "下背痛康复", fileCount: 2 },
    { id: "3-body-shame", label: "身体羞耻", group: 3, level: 3, parent: "3-biology", description: "身体意象、肥胖羞耻", fileCount: 7 },
    { id: "3-mens-health", label: "男性健康", group: 3, level: 3, parent: "3-biology", description: "男性健康议题", fileCount: 3 },
    { id: "3-std", label: "性传播疾病", group: 3, level: 3, parent: "3-biology", description: "性传播疾病科普", fileCount: 2 },
    { id: "3-paronychia", label: "甲沟炎", group: 3, level: 3, parent: "3-biology", description: "甲沟炎防治", fileCount: 2 },

    { id: "3-fasting", label: "断食", group: 3, level: 3, parent: "3-foods", description: "间歇断食、延长断食", fileCount: 5 },
    { id: "3-coffee", label: "咖啡", group: 3, level: 3, parent: "3-foods", description: "咖啡与健康", fileCount: 2 },
    { id: "3-tea", label: "茶", group: 3, level: 3, parent: "3-foods", description: "茶文化、花草茶", fileCount: 3 },
    { id: "3-fruit", label: "水果营养", group: 3, level: 3, parent: "3-foods", description: "水果营养学", fileCount: 2 },
    { id: "3-nutrition", label: "营养学", group: 3, level: 3, parent: "3-foods", description: "基础营养学", fileCount: 2 },

    { id: "3-sex-edu", label: "性教育", group: 3, level: 3, parent: "3-sexuality", description: "全面性教育", fileCount: 3 },
    { id: "3-sex-anxiety-cn", label: "中国性焦虑", group: 3, level: 3, parent: "3-sexuality", description: "中国语境下的性焦虑", fileCount: 3 },
    { id: "3-sex-repress-cn", label: "中国性压抑", group: 3, level: 3, parent: "3-sexuality", description: "中国性压抑研究", fileCount: 2 },
    { id: "3-sex-psych", label: "性心理学", group: 3, level: 3, parent: "3-sexuality", description: "性心理学基础", fileCount: 3 },
    { id: "3-male-sex", label: "男性性健康", group: 3, level: 3, parent: "3-sexuality", description: "男性性功能", fileCount: 2 },
    { id: "3-hsd", label: "性欲低下", group: 3, level: 3, parent: "3-sexuality", description: "低性欲障碍", fileCount: 2 },
    { id: "3-sex-aversion", label: "性厌恶", group: 3, level: 3, parent: "3-sexuality", description: "性厌恶障碍", fileCount: 2 },
    { id: "3-paraphilia", label: "性偏好障碍", group: 3, level: 3, parent: "3-sexuality", description: "各类性偏好", fileCount: 3 },
    { id: "3-gender-disc", label: "性别歧视", group: 3, level: 3, parent: "3-sexuality", description: "性别歧视与出生焦虑", fileCount: 2 },
    { id: "3-authority", label: "权威情结", group: 3, level: 3, parent: "3-sexuality", description: "性权威情结", fileCount: 2 },
    { id: "3-incest", label: "乱伦", group: 3, level: 3, parent: "3-sexuality", description: "乱伦创伤", fileCount: 2 },
    { id: "3-swinging", label: "多元关系", group: 3, level: 3, parent: "3-sexuality", description: "开放式关系", fileCount: 2 },
    { id: "3-masturb-sex", label: "自慰心理", group: 3, level: 3, parent: "3-sexuality", description: "自慰的心理学", fileCount: 2 },

    { id: "4-art-therapy", label: "艺术疗法", group: 4, level: 3, parent: "4-arts", description: "艺术治疗概览", fileCount: 3 },
    { id: "4-artists", label: "艺术家", group: 4, level: 3, parent: "4-arts", description: "文艺复兴与现代艺术家", fileCount: 6 },
    { id: "4-ballet", label: "芭蕾", group: 4, level: 3, parent: "4-arts", description: "技术体系、术语、教育、疗愈", fileCount: 15 },
    { id: "4-calligraphy", label: "书法疗法", group: 4, level: 3, parent: "4-arts", description: "书法与疗愈", fileCount: 4 },
    { id: "4-photography", label: "摄影疗法", group: 4, level: 3, parent: "4-arts", description: "摄影与心理疗愈", fileCount: 3 },
    { id: "4-drama", label: "戏剧疗法", group: 4, level: 3, parent: "4-arts", description: "戏剧治疗", fileCount: 4 },
    { id: "4-horticulture", label: "园艺疗法", group: 4, level: 3, parent: "4-arts", description: "园艺与自然疗愈", fileCount: 3 },
    { id: "4-craft", label: "手工疗法", group: 4, level: 3, parent: "4-arts", description: "手工制作与疗愈", fileCount: 3 },
    { id: "4-expressive", label: "表达性艺术", group: 4, level: 3, parent: "4-arts", description: "综合表达性艺术治疗", fileCount: 3 },
    { id: "4-space", label: "空间疗愈", group: 4, level: 3, parent: "4-arts", description: "空间设计与心理", fileCount: 2 },

    { id: "4-cinema", label: "电影", group: 4, level: 3, parent: "4-media", description: "影评、演员分析、电影疗法、恐怖片心理", fileCount: 120 },
    { id: "4-tv", label: "电视剧", group: 4, level: 3, parent: "4-media", description: "绝命毒师、女佣、锵锵三人行", fileCount: 20 },
    { id: "4-music", label: "音乐", group: 4, level: 3, parent: "4-media", description: "古典/民乐/古琴/歌剧/音乐治疗", fileCount: 30 },
    { id: "4-podcast", label: "播客", group: 4, level: 3, parent: "4-media", description: "播客创作指南", fileCount: 3 },
    { id: "4-anime", label: "动漫", group: 4, level: 3, parent: "4-media", description: "动漫与心理疗愈", fileCount: 2 },
    { id: "4-media-therapy", label: "媒体疗法", group: 4, level: 3, parent: "4-media", description: "媒体治疗概述", fileCount: 6 },

    { id: "4-lit-therapy", label: "文学疗法", group: 4, level: 3, parent: "4-literature", description: "莎士比亚、但丁、世界文学疗法", fileCount: 5 },
    { id: "4-lit-authors", label: "作家", group: 4, level: 3, parent: "4-literature", description: "美国现代/中世纪/文艺复兴", fileCount: 6 },
    { id: "4-lit-classical", label: "中国古典文学", group: 4, level: 3, parent: "4-literature", description: "唐诗、宋词、元曲、明清小说", fileCount: 8 },
    { id: "4-lit-poetry", label: "中国诗歌", group: 4, level: 3, parent: "4-literature", description: "现代诗、海子", fileCount: 3 },
    { id: "4-lit-modern", label: "现当代文学", group: 4, level: 3, parent: "4-literature", description: "先锋/当代/近现代", fileCount: 6 },
    { id: "4-lit-world-poetry", label: "世界诗歌", group: 4, level: 3, parent: "4-literature", description: "古典与现代世界诗歌", fileCount: 4 },

    { id: "5-super-ind", label: "超级个体", group: 5, level: 3, parent: "5-personal", description: "核心能力、商业模式、自媒体变现", fileCount: 15 },
    { id: "5-productivity", label: "生产力", group: 5, level: 3, parent: "5-personal", description: "效率核心、执行卓越", fileCount: 5 },
    { id: "5-flow", label: "心流", group: 5, level: 3, parent: "5-personal", description: "心流状态、临床应用", fileCount: 3 },
    { id: "5-resilience", label: "心力韧性", group: 5, level: 3, parent: "5-personal", description: "心理韧性建设", fileCount: 3 },
    { id: "5-core", label: "稳定内核", group: 5, level: 3, parent: "5-personal", description: "内在稳定性", fileCount: 2 },
    { id: "5-mindfulness", label: "正念生活", group: 5, level: 3, parent: "5-personal", description: "正念日常实践", fileCount: 3 },
    { id: "5-workplace", label: "职场表达", group: 5, level: 3, parent: "5-personal", description: "职场PUA、暴力沟通应对", fileCount: 20 },
    { id: "5-meta-learning", label: "元学习", group: 5, level: 3, parent: "5-personal", description: "刻意练习、学习策略", fileCount: 6 },
    { id: "5-career", label: "职业规划", group: 5, level: 3, parent: "5-personal", description: "职业发展路径", fileCount: 4 },
    { id: "5-decision", label: "决策", group: 5, level: 3, parent: "5-personal", description: "决策框架与方法", fileCount: 4 },
    { id: "5-social-cap", label: "社会资本", group: 5, level: 3, parent: "5-personal", description: "人脉与社交资本", fileCount: 3 },
    { id: "5-topics", label: "主题阅读", group: 5, level: 3, parent: "5-personal", description: "原子习惯、深度工作、高效能人士等", fileCount: 25 },
    { id: "5-focus", label: "专注力", group: 5, level: 3, parent: "5-personal", description: "注意力训练", fileCount: 2 },
    { id: "5-journaling", label: "日记", group: 5, level: 3, parent: "5-personal", description: "日记写作与自我反思", fileCount: 2 },
    { id: "5-checkin", label: "每日打卡", group: 5, level: 3, parent: "5-personal", description: "习惯追踪", fileCount: 2 },
    { id: "5-procrastination", label: "拖延", group: 5, level: 3, parent: "5-personal", description: "拖延的心理调节", fileCount: 2 },
    { id: "5-minimalism", label: "极简整理", group: 5, level: 3, parent: "5-personal", description: "极简主义与断舍离", fileCount: 2 },
    { id: "5-finance", label: "财务素养", group: 5, level: 3, parent: "5-personal", description: "理财基础", fileCount: 5 },
    { id: "5-eq", label: "情绪智力", group: 5, level: 3, parent: "5-personal", description: "情商修炼", fileCount: 2 },
    { id: "5-task", label: "任务管理", group: 5, level: 3, parent: "5-personal", description: "任务管理系统", fileCount: 2 },
    { id: "5-social-media", label: "社交媒体", group: 5, level: 3, parent: "5-personal", description: "社交媒体运营", fileCount: 3 },
    { id: "5-live-commerce", label: "直播电商", group: 5, level: 3, parent: "5-personal", description: "直播变现", fileCount: 2 },
    { id: "5-speaking", label: "公众演讲", group: 5, level: 3, parent: "5-personal", description: "演讲技巧", fileCount: 2 },
    { id: "5-pro-attraction", label: "专业吸引力", group: 5, level: 3, parent: "5-personal", description: "航空/芭蕾/教育/护理", fileCount: 4 },
    { id: "5-practice", label: "实践", group: 5, level: 3, parent: "5-personal", description: "实践练习", fileCount: 2 },

    { id: "5-effective-comm", label: "高效沟通", group: 5, level: 3, parent: "5-communication", description: "高效沟通方法", fileCount: 3 },
    { id: "5-non-defensive", label: "非防御沟通", group: 5, level: 3, parent: "5-communication", description: "非防御性沟通", fileCount: 2 },
    { id: "5-structured", label: "结构化表达", group: 5, level: 3, parent: "5-communication", description: "结构化表达能力", fileCount: 2 },
    { id: "5-coaching", label: "教练倾听", group: 5, level: 3, parent: "5-communication", description: "教练式倾听", fileCount: 2 },
    { id: "5-negotiation", label: "谈判", group: 5, level: 3, parent: "5-communication", description: "谈判心理学与策略", fileCount: 3 },

    { id: "5-tech-writing", label: "技术写作", group: 5, level: 3, parent: "5-writing", description: "API文档、DevOps、本地化", fileCount: 9 },

    { id: "5-ted", label: "TED Talks", group: 5, level: 3, parent: "5-talks", description: "AI/宇宙学/经济学等 150+ 领域", fileCount: 70 },
    { id: "5-yixi", label: "一席讲座", group: 5, level: 3, parent: "5-talks", description: "自治学习、文明对话、音乐、医学", fileCount: 4 },
    { id: "5-framework", label: "框架", group: 5, level: 3, parent: "5-talks", description: "讲座知识框架", fileCount: 3 },
    { id: "5-round-table", label: "圆桌", group: 5, level: 3, parent: "5-talks", description: "圆桌讨论", fileCount: 2 },
    { id: "5-talks-psych", label: "心理学讲座", group: 5, level: 3, parent: "5-talks", description: "心理学专题讲座", fileCount: 3 }
  ],

  links: [
    { source: "root", target: "p1", type: "hierarchy" },
    { source: "root", target: "p2", type: "hierarchy" },
    { source: "root", target: "p3", type: "hierarchy" },
    { source: "root", target: "p4", type: "hierarchy" },
    { source: "root", target: "p5", type: "hierarchy" },

    { source: "p1", target: "1-philosophy", type: "hierarchy" },
    { source: "p1", target: "1-religions", type: "hierarchy" },
    { source: "p1", target: "1-tai-chi", type: "hierarchy" },
    { source: "p1", target: "1-tcm", type: "hierarchy" },
    { source: "p1", target: "1-yoga", type: "hierarchy" },

    { source: "1-philosophy", target: "1-east-asian", type: "hierarchy" },
    { source: "1-philosophy", target: "1-south-asian", type: "hierarchy" },
    { source: "1-philosophy", target: "1-western-phil", type: "hierarchy" },

    { source: "1-religions", target: "1-buddhism", type: "hierarchy" },
    { source: "1-religions", target: "1-zen", type: "hierarchy" },
    { source: "1-religions", target: "1-dao", type: "hierarchy" },
    { source: "1-religions", target: "1-tibetan", type: "hierarchy" },
    { source: "1-religions", target: "1-christianity", type: "hierarchy" },
    { source: "1-religions", target: "1-catholicism", type: "hierarchy" },
    { source: "1-religions", target: "1-orthodox", type: "hierarchy" },
    { source: "1-religions", target: "1-islam", type: "hierarchy" },
    { source: "1-religions", target: "1-legalist", type: "hierarchy" },
    { source: "1-religions", target: "1-syncretism", type: "hierarchy" },
    { source: "1-religions", target: "1-rel-psych", type: "hierarchy" },
    { source: "1-religions", target: "1-wisdom", type: "hierarchy" },

    { source: "1-tcm", target: "1-tcm-classics", type: "hierarchy" },

    { source: "1-yoga", target: "1-yoga-asana", type: "hierarchy" },
    { source: "1-yoga", target: "1-yoga-masters", type: "hierarchy" },
    { source: "1-yoga", target: "1-yoga-career", type: "hierarchy" },
    { source: "1-yoga", target: "1-yoga-training", type: "hierarchy" },
    { source: "1-yoga", target: "1-yoga-six", type: "hierarchy" },
    { source: "1-yoga", target: "1-yoga-safety", type: "hierarchy" },

    { source: "p2", target: "2-meditation", type: "hierarchy" },
    { source: "p2", target: "2-psychology", type: "hierarchy" },
    { source: "p2", target: "2-relationships", type: "hierarchy" },
    { source: "p2", target: "2-therapy", type: "hierarchy" },

    { source: "2-meditation", target: "2-med-overview", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-masters", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-course", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-guided", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-mbsr", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-direct", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-mandala", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-satir", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-tm", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-vipassana", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-chinese", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-career", type: "hierarchy" },
    { source: "2-meditation", target: "2-med-training", type: "hierarchy" },

    { source: "2-psychology", target: "2-psych-foundations", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-clinical", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-stress", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-dev", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-social", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-behav", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-somatic", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-selfreg", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-applied", type: "hierarchy" },
    { source: "2-psychology", target: "2-psych-special", type: "hierarchy" },

    { source: "2-relationships", target: "2-rel-infidelity", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-marriage", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-dating", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-gender", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-eba", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-love", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-parenting", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-casual", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-cultural", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-clinical", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-digital", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-diverse", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-impact", type: "hierarchy" },
    { source: "2-relationships", target: "2-rel-legal", type: "hierarchy" },

    { source: "2-therapy", target: "2-ther-cbt", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-dbt", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-act", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-mbct", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-cft", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-emdr", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-tfcbt", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-cbasp", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-morita", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-oh", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-focus", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-game", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-ipt", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-sensory", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-forest", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-incense", type: "hierarchy" },
    { source: "2-therapy", target: "2-ther-direct", type: "hierarchy" },

    { source: "p3", target: "3-biology", type: "hierarchy" },
    { source: "p3", target: "3-foods", type: "hierarchy" },
    { source: "p3", target: "3-sexuality", type: "hierarchy" },
    { source: "p3", target: "3-death", type: "hierarchy" },

    { source: "3-biology", target: "3-exercise", type: "hierarchy" },
    { source: "3-biology", target: "3-aging", type: "hierarchy" },
    { source: "3-biology", target: "3-cardio", type: "hierarchy" },
    { source: "3-biology", target: "3-gut", type: "hierarchy" },
    { source: "3-biology", target: "3-immune", type: "hierarchy" },
    { source: "3-biology", target: "3-brain", type: "hierarchy" },
    { source: "3-biology", target: "3-hpa", type: "hierarchy" },
    { source: "3-biology", target: "3-weight", type: "hierarchy" },
    { source: "3-biology", target: "3-tuina", type: "hierarchy" },
    { source: "3-biology", target: "3-spa", type: "hierarchy" },
    { source: "3-biology", target: "3-skin", type: "hierarchy" },
    { source: "3-biology", target: "3-floaters", type: "hierarchy" },
    { source: "3-biology", target: "3-breathwork", type: "hierarchy" },
    { source: "3-biology", target: "3-women", type: "hierarchy" },
    { source: "3-biology", target: "3-bp", type: "hierarchy" },
    { source: "3-biology", target: "3-energy", type: "hierarchy" },
    { source: "3-biology", target: "3-office-neck", type: "hierarchy" },
    { source: "3-biology", target: "3-office-eye", type: "hierarchy" },
    { source: "3-biology", target: "3-sleep-stretch", type: "hierarchy" },
    { source: "3-biology", target: "3-stretch", type: "hierarchy" },
    { source: "3-biology", target: "3-pain", type: "hierarchy" },
    { source: "3-biology", target: "3-back-pain", type: "hierarchy" },
    { source: "3-biology", target: "3-body-shame", type: "hierarchy" },
    { source: "3-biology", target: "3-mens-health", type: "hierarchy" },
    { source: "3-biology", target: "3-std", type: "hierarchy" },
    { source: "3-biology", target: "3-paronychia", type: "hierarchy" },

    { source: "3-foods", target: "3-fasting", type: "hierarchy" },
    { source: "3-foods", target: "3-coffee", type: "hierarchy" },
    { source: "3-foods", target: "3-tea", type: "hierarchy" },
    { source: "3-foods", target: "3-fruit", type: "hierarchy" },
    { source: "3-foods", target: "3-nutrition", type: "hierarchy" },

    { source: "3-sexuality", target: "3-sex-edu", type: "hierarchy" },
    { source: "3-sexuality", target: "3-sex-anxiety-cn", type: "hierarchy" },
    { source: "3-sexuality", target: "3-sex-repress-cn", type: "hierarchy" },
    { source: "3-sexuality", target: "3-sex-psych", type: "hierarchy" },
    { source: "3-sexuality", target: "3-male-sex", type: "hierarchy" },
    { source: "3-sexuality", target: "3-hsd", type: "hierarchy" },
    { source: "3-sexuality", target: "3-sex-aversion", type: "hierarchy" },
    { source: "3-sexuality", target: "3-paraphilia", type: "hierarchy" },
    { source: "3-sexuality", target: "3-gender-disc", type: "hierarchy" },
    { source: "3-sexuality", target: "3-authority", type: "hierarchy" },
    { source: "3-sexuality", target: "3-incest", type: "hierarchy" },
    { source: "3-sexuality", target: "3-swinging", type: "hierarchy" },
    { source: "3-sexuality", target: "3-masturb-sex", type: "hierarchy" },

    { source: "p4", target: "4-arts", type: "hierarchy" },
    { source: "p4", target: "4-media", type: "hierarchy" },
    { source: "p4", target: "4-literature", type: "hierarchy" },
    { source: "p4", target: "4-reading", type: "hierarchy" },

    { source: "4-arts", target: "4-art-therapy", type: "hierarchy" },
    { source: "4-arts", target: "4-artists", type: "hierarchy" },
    { source: "4-arts", target: "4-ballet", type: "hierarchy" },
    { source: "4-arts", target: "4-calligraphy", type: "hierarchy" },
    { source: "4-arts", target: "4-photography", type: "hierarchy" },
    { source: "4-arts", target: "4-drama", type: "hierarchy" },
    { source: "4-arts", target: "4-horticulture", type: "hierarchy" },
    { source: "4-arts", target: "4-craft", type: "hierarchy" },
    { source: "4-arts", target: "4-expressive", type: "hierarchy" },
    { source: "4-arts", target: "4-space", type: "hierarchy" },

    { source: "4-media", target: "4-cinema", type: "hierarchy" },
    { source: "4-media", target: "4-tv", type: "hierarchy" },
    { source: "4-media", target: "4-music", type: "hierarchy" },
    { source: "4-media", target: "4-podcast", type: "hierarchy" },
    { source: "4-media", target: "4-anime", type: "hierarchy" },
    { source: "4-media", target: "4-media-therapy", type: "hierarchy" },

    { source: "4-literature", target: "4-lit-therapy", type: "hierarchy" },
    { source: "4-literature", target: "4-lit-authors", type: "hierarchy" },
    { source: "4-literature", target: "4-lit-classical", type: "hierarchy" },
    { source: "4-literature", target: "4-lit-poetry", type: "hierarchy" },
    { source: "4-literature", target: "4-lit-modern", type: "hierarchy" },
    { source: "4-literature", target: "4-lit-world-poetry", type: "hierarchy" },

    { source: "p5", target: "5-personal", type: "hierarchy" },
    { source: "p5", target: "5-communication", type: "hierarchy" },
    { source: "p5", target: "5-writing", type: "hierarchy" },
    { source: "p5", target: "5-talks", type: "hierarchy" },

    { source: "5-personal", target: "5-super-ind", type: "hierarchy" },
    { source: "5-personal", target: "5-productivity", type: "hierarchy" },
    { source: "5-personal", target: "5-flow", type: "hierarchy" },
    { source: "5-personal", target: "5-resilience", type: "hierarchy" },
    { source: "5-personal", target: "5-core", type: "hierarchy" },
    { source: "5-personal", target: "5-mindfulness", type: "hierarchy" },
    { source: "5-personal", target: "5-workplace", type: "hierarchy" },
    { source: "5-personal", target: "5-meta-learning", type: "hierarchy" },
    { source: "5-personal", target: "5-career", type: "hierarchy" },
    { source: "5-personal", target: "5-decision", type: "hierarchy" },
    { source: "5-personal", target: "5-social-cap", type: "hierarchy" },
    { source: "5-personal", target: "5-topics", type: "hierarchy" },
    { source: "5-personal", target: "5-focus", type: "hierarchy" },
    { source: "5-personal", target: "5-journaling", type: "hierarchy" },
    { source: "5-personal", target: "5-checkin", type: "hierarchy" },
    { source: "5-personal", target: "5-procrastination", type: "hierarchy" },
    { source: "5-personal", target: "5-minimalism", type: "hierarchy" },
    { source: "5-personal", target: "5-finance", type: "hierarchy" },
    { source: "5-personal", target: "5-eq", type: "hierarchy" },
    { source: "5-personal", target: "5-task", type: "hierarchy" },
    { source: "5-personal", target: "5-social-media", type: "hierarchy" },
    { source: "5-personal", target: "5-live-commerce", type: "hierarchy" },
    { source: "5-personal", target: "5-speaking", type: "hierarchy" },
    { source: "5-personal", target: "5-pro-attraction", type: "hierarchy" },
    { source: "5-personal", target: "5-practice", type: "hierarchy" },

    { source: "5-communication", target: "5-effective-comm", type: "hierarchy" },
    { source: "5-communication", target: "5-non-defensive", type: "hierarchy" },
    { source: "5-communication", target: "5-structured", type: "hierarchy" },
    { source: "5-communication", target: "5-coaching", type: "hierarchy" },
    { source: "5-communication", target: "5-negotiation", type: "hierarchy" },

    { source: "5-writing", target: "5-tech-writing", type: "hierarchy" },

    { source: "5-talks", target: "5-ted", type: "hierarchy" },
    { source: "5-talks", target: "5-yixi", type: "hierarchy" },
    { source: "5-talks", target: "5-framework", type: "hierarchy" },
    { source: "5-talks", target: "5-round-table", type: "hierarchy" },
    { source: "5-talks", target: "5-talks-psych", type: "hierarchy" },

    { source: "1-buddhism", target: "2-meditation", type: "cross-ref", label: "止观→正念冥想" },
    { source: "1-buddhism", target: "2-therapy", type: "cross-ref", label: "佛学心理→MBCT" },
    { source: "1-dao", target: "2-psych-special", type: "cross-ref", label: "道家养生→中医心理" },
    { source: "1-yoga", target: "2-ther-act", type: "cross-ref", label: "瑜伽→ACT" },
    { source: "1-yoga", target: "2-psych-somatic", type: "cross-ref", label: "瑜伽疗愈→躯体疗法" },
    { source: "1-wisdom", target: "2-meditation", type: "cross-ref", label: "克里希那穆提→冥想" },
    { source: "1-yoga", target: "3-stretch", type: "cross-ref", label: "瑜伽解剖→拉伸" },
    { source: "1-tcm", target: "3-hpa", type: "cross-ref", label: "内经→HPA轴" },
    { source: "1-tai-chi", target: "3-energy", type: "cross-ref", label: "太极→能量恢复" },
    { source: "1-yoga", target: "3-brain", type: "cross-ref", label: "瑜伽→脑科学" },
    { source: "2-psych-somatic", target: "3-sleep-stretch", type: "cross-ref", label: "睡眠→睡前拉伸" },
    { source: "2-psych-stress", target: "3-hpa", type: "cross-ref", label: "压力→HPA轴" },
    { source: "2-meditation", target: "3-brain", type: "cross-ref", label: "冥想→神经科学" },
    { source: "2-psych-behav", target: "3-sexuality", type: "cross-ref", label: "成瘾→性焦虑" },
    { source: "2-ther-sensory", target: "4-arts", type: "cross-ref", label: "感官→艺术疗法" },
    { source: "2-ther-sensory", target: "4-expressive", type: "cross-ref", label: "舞动→表达艺术" },
    { source: "2-ther-sensory", target: "4-music", type: "cross-ref", label: "声音→音乐治疗" },
    { source: "2-psych-applied", target: "5-productivity", type: "cross-ref", label: "职业→效率" },
    { source: "2-psych-applied", target: "5-workplace", type: "cross-ref", label: "职场危机→表达" },
    { source: "2-psych-applied", target: "5-resilience", type: "cross-ref", label: "倦怠→心力" },
    { source: "2-meditation", target: "5-mindfulness", type: "cross-ref", label: "冥想→正念生活" },
    { source: "1-buddhism", target: "2-psych-applied", type: "cross-ref", label: "四无量心→倦怠" },
    { source: "1-tai-chi", target: "2-psych-applied", type: "cross-ref", label: "太极→压力调节" },
    { source: "1-yoga", target: "2-psych-applied", type: "cross-ref", label: "瑜伽→倦怠干预" },
    { source: "1-zen", target: "2-psych-applied", type: "cross-ref", label: "禅宗→职场心流" },
    { source: "2-psych-stress", target: "2-psych-clinical", type: "cross-ref", label: "HPA→焦虑共病" },
    { source: "2-psych-applied", target: "2-psych-clinical", type: "cross-ref", label: "倦怠→抑郁鉴别" },
    { source: "2-psych-applied", target: "2-psych-stress", type: "cross-ref", label: "倦怠→慢性疲劳" },
    { source: "2-psych-applied", target: "2-therapy", type: "cross-ref", label: "倦怠→CBT/ACT" }
  ]
};
